### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by hadhoryth** [dansiegel/Prism.Plugin.PageDialogs#3]
Hi Dan, 
I'm trying to use your plugin but I can't register it in my app:
`Container.Register <IPageDialogService,CustomPageDialogService>();`

Error: IUnityContainer does not contain a definition for Register

**Comment by hadhoryth** [comment]
I figured out how to solve that problem. -> just using the `RegisterType`.
Also I had issues with building my project in release mode. The schema in Xamarin Studio which I'm using is `PCL4.5 - Profile78`, so I had to rebuild source codes for `PageDialogs` and `Unity` for my targets and I had to remove XAML compilation because it cases an error.
But the plugin is great.

**Comment by dansiegel** [comment]
@hadhoryth glad you figured it out and that it's working great for you. Remember the plugin is still an early preview. I'll hopefully be getting a pre2 release this weekend or next week.
